version: '3'
 
services:
  postgresserver:
    image: postgres:latest
    container_name: db
    restart: always
    user: postgres
    environment: 
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "4LabDev"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  api:
    image: 4lab-api
    container_name: 
      api
    ports:
      - 5000:80
    environment: 
      CONNECTION: "User ID=postgres;Password=docker;Host=postgresserver;Port=5432;Database=4LabDev;Pooling=true;"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresserver
    depends_on:
      postgresserver:
         condition: service_healthy
    command: ["./wait-for-it.sh", "postgresserver:5432", "--", "python", "app.py"]  
    networks:
      - mynetwork

volumes:
  pgdata:
networks:
  mynetwork:
     driver: bridge