name: Deploy AWS

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
    - name: Zip-Package
      run : | 
        cd '${{ github.workspace }}/out'
        7z a -tzip ${{ github.workspace }}/out.zip ${{ github.workspace }}/out
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: rnc
        environment_name: Rnc-env
        version_label: ${{github.run_id}}
        region: us-east-1
        deployment_package: ${{ github.workspace }}/out.zip
